### ISSUE TITLE
Dev and build commands not working

### ISSUE THREAD

**Issue by ashNotKetchup** [goldsmocap/mocap-streamer#9]
At the moment, nothing will build, argh! Will add error logs as and when I come across them. 

Replicate:

- Fetch the latest update from repo (I'm also intrigued to see if this happens with old copies too)
- Open terminal in that folder
- Try either Dev(`yarn` then `yarn local dev`) or Build (`yarn` then `yarn local build`)

Questions:

- Does this happen with windows machines? 
- What errors is everyone else getting?

**Comment by demzou** [comment]
Test building on windows machine. Build successful but error once launching the app:

```
Uncaught Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at ry (index.js:17:11)
    at index.js:21:18
```

**Comment by ashNotKetchup** [comment]
Looking into this a little more, seems like it could be an issue with using import rather than require? Or with requiring something we shouldn't be?

For example:

https://github.com/electron/electron/issues/7300#issuecomment-274269710

**Comment by ashNotKetchup** [comment]
Seems like there has been an issue with broken dependencies relating to electron (specifically ipcRenderer) following an update. We're not sure which so we have temporarily solved this by committing Oli's yarn.lock file to the repo. This has the effect of locking all dependencies to specific versions specified in that lock file, guaranteeing that anyone who pulls this file will get those versions (which work).

Something has changed in electron/its typescript definitions, we need to upgrade the dependencies to the latest version and figure out what has gone wrong.

**Comment by ashNotKetchup** [comment]
Possible methods for figuring out broken dependencies:

- Yarn.lock file comparison
- Upgrade single dependencies one at a time using `yarn upgrade-interactive`
